### ISSUE TITLE
[FEATURE] List rooms user is in

### ISSUE THREAD

**Issue by Dan-tha-man** [fax-group/fax_app_cli#1]
**Is your feature request related to a problem? Please describe.**
return a list of all of the rooms available to the user

**Describe the solution you'd like**

- [x] list out rooms

**Describe alternatives you've considered**
N/A

**Additional context**
dart [http](https://pub.dev/documentation/http/latest/) package

**Comment by NADEE-MJ** [comment]
Added method in user class to list out all rooms that user is in.
