### ISSUE TITLE
[FEATURE] Create a room

### ISSUE THREAD

**Issue by Dan-tha-man** [fax-group/fax_app_cli#3]
**Is your feature request related to a problem? Please describe.**
Create and access rooms

**Describe the solution you'd like**
- [x] create new rooms
- [x] invite people to rooms
- [ ] sync up events with room

**Additional context**

dart [http](https://pub.dev/documentation/http/latest/) package

**Comment by NADEE-MJ** [comment]
syncing events of a room is a part of #7, this issue has been completed otherwise, will close and continue working on  #7.
