### ISSUE TITLE
[FEATURE] change transaction ID generation

### ISSUE THREAD

**Issue by NADEE-MJ** [fax-group/fax_app_cli#6]
**Is your feature request related to a problem? Please describe.**
Currently, transaction IDs are generated by creating a random alphanumeric 10 digit string.

**Describe the solution you'd like**

- [ ] new transaction ID generation for events

**Additional context**
[dart](https://spec.matrix.org/v1.2/client-server-api/) client-server api

**Comment by aaronfrank123** [comment]
Since the TID is used only to distinguish between a message that has been sent and a message that hasn't, a random string should do the job fine. If we were to use the TID for anything more complex than that though, then we should re-open the issue.
